server:
  port: 8090

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.1.130
  rabbitmq:
    host: 192.168.1.130
    username: huage
    password: huage
    virtual-host: /huage
    port: 5672

gmall:
  jwt:
    pubKeyPath: D:\\temp\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
    userKey: user-key

